travis:
  secure:
    BINSTAR_TOKEN: mdQQkguwPeTdwNee7eFLwKyZz7g/WOMUtyAANprGZQURYBK94uZAGFwMjUqlzM5KWpu9igQo8JJikxt1GmVqgbRW29DaNiVvzDZ6sYBU63CZrS0Dy1CNCyoUMp8KVceEX9KBgzIarBf7lfttV5mvOJkTgGRB953DupwvRb0szsrwvsmd/4LmzJIMTMZC0tdkENgdzl/hPd06Y6cX7V7D9m93q2nKO1J7rzBfNwxV8yE0rxiBqvkWvcrKfrxngz4c652C5HXOsf0EMUb9ts1D65cOnMR01zYm5FzKUc39m+GpY2ix6T4DkX7gaNPbzCr+c43NLLkP517qxT12RKHhGKYjszaldwV/95zCWa/v3k9IK5IsZDv0DiVKzKabZSnQ6zR1qa/VgtqJyQgF3y/yRzZSEAIIiVZSCBM8x+7jtUqYS7hfZxgpx3/2yeGYeru6bYLFyouOAd1eAkxEOTaXBJWWP1o1Saj5CbxPv9L1b/XrSegOVrbL/6yQBUdxkOK6SzzAi67RKKpL/Y3zW65uR/GDx+/P7xcw2rQqrWwkoK5zFnAHHerO85oT950hgm1Cz4TStNK9F+ZoqA3gi2+NF6PeK9CXdy9ekvAZjr3BFClgJsEuAGvsouXjroNcukvMMj/JYg8kUKzVoqGY0GwYrapnD6iDS2LqAQGXaZD8bsw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
